# Generated by Django 5.0.2 on 2024-02-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_score',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
