# Generated by Django 5.0.2 on 2024-02-20 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_review_review_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_score',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ReviewScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.review')),
            ],
        ),
    ]
