# Generated by Django 5.0.2 on 2024-02-20 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_review_review_score_alter_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTotalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
