# Generated by Django 5.0.2 on 2024-02-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_producttotalscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttotalscore',
            name='total_score',
            field=models.FloatField(),
        ),
    ]
