# Generated by Django 5.0.2 on 2024-02-20 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_producttopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion1', models.CharField(max_length=100)),
                ('emotion2', models.CharField(max_length=100)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.review')),
            ],
        ),
    ]
